dist: trusty
language: go

services:
  - docker

go:
  - "1.11"

# This build should not be triggered by tags
if: tags IS blank

env:
  global:
    - BRANCH=$([ ${TRAVIS_BRANCH} == master ] && echo latest || echo ${TRAVIS_BRANCH})

before_install:
  - configure_jfrog_client
  - helm init --client-only

install:
  # Installing pact-go dependencies
  - curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.70.2/pact-1.70.2-linux-x86_64.tar.gz
  - tar xzf pact-1.70.2-linux-x86_64.tar.gz -C $HOME --strip-components 1
  - export PATH=$PATH:$HOME/pact/bin
  - make setup    

# script always run to completion (set +e). All of these code checks are must haves
# in a modern Go project.
script:
  # Generate coverage and checkstyle report
  - make test

after_failure:
  - reports-publisher

after_success:
  - reports-publisher

deploy:
  - provider: script
    script: make docker-build docker-publish
    on:
      all_branches: true
      condition: $TRAVIS_PULL_REQUEST = false
  - provider: script
    script: make helm-publish
    on:
      all_branches: true
      condition: $TRAVIS_PULL_REQUEST = false

